### ISSUE TITLE
Login & Validate account with email

### ISSUE THREAD

**Issue by lomholdt** [lomholdt/la-pizzeria#11]
is a valid email address which is done by sending a 4-digit number to the email address along with a link to a page where the key has to be entered before registration is completed

**Comment by nielsdaw** [comment]
Stoped: At validat.jsp, and Validate Mail/Pin Controller.

challenges: To send email parameter in url, and validate with db.

**Comment by jonastonny** [comment]
ValidatePinController
Få mail med videre fra ValidateEmail

**Comment by jonastonny** [comment]
Notes:
- Fix URL problem for createuser når oprettelsen godkendes og man sendes videre til validate. Lige nu står der /createuser i URL'en - email sendes dog med så brugeren kan indtaste pin på den side.
- Fix (samme) URL problem for validate når pinkoden godkendes. Lige nu lader jeg brugeren blive på siden med en lille besked. Brugeren skal helst sendes videre til login med en besked om at registreringen er godkendt.
- Fix: Flere brugere må ikke have samme mail...
- Slettet: ValidateMailController er blevet overflødig - overtaget af ValidatePinController
- Slettet: UserController er blevet overflødig - overtaget af CreateUserController
