### ISSUE TITLE
Dynamically create some html (input) elements and insert them into DOM and parse them

### ISSUE THREAD

**Issue by lomholdt** [lomholdt/la-pizzeria#16]
For example, the user wants to have some additional toppings on his
pizza and you don’t know how many toppings the user wishes to have!
Therefore, one scenario could be to have a toppings button, which will
create a new input field dynamically on each click event.
This is only a suggestion, you are free to come-up with your own creative
ideas and implement them in your web shop.

**Comment by nielsdaw** [comment]
Add Toppings:
- Dropdown/Checkbox for additional toppings
- Add the toppings to pizza in session

**Comment by lomholdt** [comment]
I må gerne teste custom pizz. Jeg er ikke sikker på, at alle huller er lukket ift. parametre og tomme felter.
