### ISSUE TITLE
AJAX - Contact a web server and get some information asynchronously using JavaScript.

### ISSUE THREAD

**Issue by lomholdt** [lomholdt/la-pizzeria#17]
As a simple example, you may get a picture for your pizza from Flickr, or
you may call some kind of translation service provided by companies like
Google/Microsoft using AJAX functionality and translate your pizza menu
texts (or some other text) into a another language. Alternatively, you may
also keep some text on the server (may be in the form of a file) and get
that information from client side, using AJAX functionality, to display it on
the web page.
Again you are welcome to come up with some creative ideas and
implement those.

**Comment by nielsdaw** [comment]
Mouseover:
- Search/pull pizzas from flickr
- fx. searching for "pizza" + pizzaName
